const API="https://script.google.com/macros/s/AKfycbzjFU-GS5vyCESo4tji-g1g52f73uodE7SFFO1U13cRN88bcSiklfARWfbi5V2KhrsCLg/exec";const $=id=>document.getElementById(id);let allHistory=[],rooms=[],inspectors=[],supervisors=[];let pinUnlocked=false,hasPin=false,pinSession="",pendingProtectedTab="";let scanStream=null,scanTimer=null,scanCanvas=null,scanCtx=null;
document.addEventListener("DOMContentLoaded",async()=>{bindTabs();$("startModeBtn").onclick=()=>setMode("Start Sampling");$("finishModeBtn").onclick=()=>setMode("Finish Sampling");$("btnSave").onclick=saveSampling;$("btnRefresh").onclick=loadAll;$("btnSupervisorRefresh").onclick=loadSupervisor;$("closePin").onclick=closePinModal;$("pinSubmit").onclick=submitPin;$("savePin").onclick=savePin;$("txtSearch").oninput=renderHistory;$("historyRoom").onchange=renderHistory;$("historyStatus").onchange=renderHistory;$("supervisorRoom").onchange=renderSupervisor;$("approveBy").onchange=renderSupervisor;$("btnExport").onclick=exportCSV;$("addRoom").onclick=addRoom;$("addInspector").onclick=addInspector;$("addSupervisor").onclick=addSupervisor;$("scanButton").onclick=openScanner;$("closeScanner").onclick=closeScanner;$("useQrManual").onclick=useManualQr;["code","batch"].forEach(id=>$(id).addEventListener("input",e=>e.target.value=e.target.value.toUpperCase()));["incomingCarton","remainderCartonIn","remainderQtyIn","qtyFullCartonIn"].forEach(id=>$(id).addEventListener("input",calcStart));["remainderCartonOut","remainderQtyOut","fullCartonOut","qtyFullCartonOut","sampleUsage","totalCartonOut"].forEach(id=>$(id).addEventListener("input",calcFinish));$("unit").onchange=updateUnitLabels;setMode("Start Sampling");await loadMaster();await loadAll();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{});setInterval(loadAll,15000)});
function bindTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{const id=b.dataset.tab;if(id==="supervisorTab"||id==="settingsTab"){openProtectedTab(id);return}activateTab(id)});}
function activateTab(id){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".tabPanel").forEach(x=>x.classList.remove("active"));const btn=document.querySelector(`[data-tab="${id}"]`);if(btn)btn.classList.add("active");$(id).classList.add("active");if(id==="historyTab")loadHistory();if(id==="supervisorTab")loadSupervisor();if(id==="settingsTab")renderSettings();}
function openProtectedTab(id){pendingProtectedTab=id;if(!hasPin){if(id==="settingsTab"){openPinSetup();}else{toast("ยังไม่ได้ตั้ง PIN กรุณาเข้า Settings เพื่อตั้ง PIN ก่อน","error");activateTab("samplingTab")}return}$("pinTitle").textContent="🔐 กรุณาใส่ PIN";$("pinMessage").textContent=id==="supervisorTab"?"ต้องใส่ PIN ก่อนเข้า Approve":"ต้องใส่ PIN ก่อนเข้า Settings";$("pinLabel").textContent="PIN";$("pinInput").value="";$("pinConfirm").value="";$("pinNewWrap").classList.add("hidden");$("pinSubmit").textContent="ยืนยัน";$("pinModal").classList.remove("hidden");setTimeout(()=>$("pinInput").focus(),80)}
function openPinSetup(){pendingProtectedTab="settingsTab";$("pinTitle").textContent="🔐 ตั้ง PIN ครั้งแรก";$("pinMessage").textContent="ตั้ง PIN สำหรับหน้า Approve และ Settings";$("pinLabel").textContent="PIN ใหม่";$("pinInput").value="";$("pinConfirm").value="";$("pinNewWrap").classList.remove("hidden");$("pinSubmit").textContent="ตั้ง PIN";$("pinModal").classList.remove("hidden");setTimeout(()=>$("pinInput").focus(),80)}
function closePinModal(){$("pinModal").classList.add("hidden");$("pinInput").value="";$("pinConfirm").value=""}
async function submitPin(){const pin=$("pinInput").value.trim();if(!pin)return toast("กรุณากรอก PIN","error");if(!/^\d{4,12}$/.test(pin))return toast("PIN ต้องเป็นตัวเลข 4-12 หลัก","error");if(!hasPin){const confirmPin=$("pinConfirm").value.trim();if(pin!==confirmPin)return toast("PIN ยืนยันไม่ตรงกัน","error");const j=await postJson({action:"setPin",newPin:pin});if(!j.success)return toast(j.message,"error");hasPin=true;pinUnlocked=true;pinSession=pin;closePinModal();toast("ตั้ง PIN สำเร็จ","success");activateTab("settingsTab");renderSettings();return}const j=await postJson({action:"verifyPin",pin});if(!j.success)return toast("PIN ไม่ถูกต้อง","error");pinUnlocked=true;pinSession=pin;closePinModal();toast("ยืนยัน PIN สำเร็จ","success");activateTab(pendingProtectedTab)}
async function savePin(){if(!pinUnlocked)return openProtectedTab("settingsTab");const current=$("currentPin").value.trim(),next=$("newPin").value.trim();if(!/^\d{4,12}$/.test(next))return toast("PIN ใหม่ต้องเป็นตัวเลข 4-12 หลัก","error");const j=await postJson({action:"setPin",currentPin:current,newPin:next,pin:pinSession});if(!j.success)return toast(j.message,"error");pinSession=next;hasPin=true;$("currentPin").value="";$("newPin").value="";toast("เปลี่ยน PIN สำเร็จ","success")}
function setMode(m){$("status").value=m;const f=m==="Finish Sampling";$("startModeBtn").classList.toggle("active",!f);$("finishModeBtn").classList.toggle("active",f);$("startFields").classList.toggle("hidden",f);$("finishFields").classList.toggle("hidden",!f);$("balanceAlert").classList.add("hidden");if(f)loadStartForFinish();updateUnitLabels()}
function updateUnitLabels(){document.querySelectorAll(".unitLabel").forEach(e=>e.textContent=$("unit").value)}
function calcStart(){const incoming=Number($("incomingCarton").value||0),total=incoming>0?Math.ceil(Math.sqrt(incoming)+1):0;$("totalCartonIn").value=total||"";const rem=Number($("remainderCartonIn").value||0),full=Math.max(0,total-rem);$("fullCartonIn").value=total?full:"";const q=Number($("qtyFullCartonIn").value||0),rq=Number($("remainderQtyIn").value||0),sample=full*q+rq;$("sampleInPreview").textContent=sample}
function calcFinish(){const total=Number($("totalCartonOut").value||0),rem=Number($("remainderCartonOut").value||0),full=Number($("fullCartonOut").value||0),q=Number($("qtyFullCartonOut").value||0),rq=Number($("remainderQtyOut").value||0),out=full*q+rq,use=Number($("sampleUsage").value||0);$("sampleOutPreview").textContent=out;const incoming=Number($("_incomingForFinish")?.value||0);if(incoming){const bal=incoming-out-use;$("balancePreview").textContent=Math.abs(bal)<1e-9?"✅ Balance OK":"⚠️ ต่าง "+bal}}
function hiddenIncoming(){let e=$("_incomingForFinish");if(!e){e=document.createElement("input");e.id="_incomingForFinish";e.type="hidden";document.body.appendChild(e)}return e}
async function loadStartForFinish(){const code=$("code").value.trim(),batch=$("batch").value.trim();if(!code||!batch)return;try{const j=await getJson(API+"?action=history");const x=(j.data||[]).find(a=>a.code===code.toUpperCase()&&a.batch===batch.toUpperCase()&&a.status==="Sampling");if(x){hiddenIncoming().value=x.sampleIn;$("unit").value=x.unit||"pcs";updateUnitLabels();calcFinish();}}catch(_){} }
async function getJson(u){const r=await fetch(u,{cache:"no-store"});return r.json()}async function postJson(b){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(b)});return r.json()}
async function loadMaster(){try{const [r,i,s,pin]=await Promise.all([getJson(API+"?action=rooms"),getJson(API+"?action=inspectors"),getJson(API+"?action=supervisors"),getJson(API+"?action=pinStatus")]);if(!r.success||!i.success||!s.success||!pin.success)throw Error("โหลด Master ไม่สำเร็จ");rooms=r.data||[];inspectors=i.data||[];supervisors=s.data||[];hasPin=!!pin.data?.hasPin;fillMasters();renderSettings();setOnline()}catch(e){setOffline();toast("โหลด Room/Inspector/Supervisor ไม่สำเร็จ","error")}}
function fillMasters(){$("room").innerHTML='<option value="">— เลือก Room —</option>'+rooms.map(x=>`<option>${esc(x.room)}</option>`).join("");$("inspector").innerHTML='<option value="">— ยังไม่เลือก Inspector —</option>'+inspectors.map(x=>`<option>${esc(x.inspector)}</option>`).join("");$("historyRoom").innerHTML='<option value="">ทุกห้อง</option>'+rooms.map(x=>`<option>${esc(x.room)}</option>`).join("");$("supervisorRoom").innerHTML='<option value="">ทุกห้อง</option>'+rooms.map(x=>`<option>${esc(x.room)}</option>`).join("");fillApprovers()}
function fillApprovers(){$("approveBy").innerHTML='<option value="">— เลือกผู้อนุมัติ —</option>'+supervisors.map(x=>`<option value="${esc(x.supervisor)}">${esc(x.supervisor)}</option>`).join("")}
async function loadAll(){try{const [d,h]=await Promise.all([getJson(API+"?action=dashboard"),getJson(API+"?action=history")]);if(!d.success||!h.success)throw Error("โหลดข้อมูลไม่สำเร็จ");renderDashboard(d.data);allHistory=h.data||[];renderHistory();renderSupervisor();setOnline()}catch(e){setOffline()}}
async function loadHistory(){try{const h=await getJson(API+"?action=history");if(h.success){allHistory=h.data||[];renderHistory()}}catch(_){} }
function renderDashboard(d){const s=d.samplingNow||[],c=d.completedToday||[];$("samplingNow").textContent=s.length;$("completedToday").textContent=c.length;$("totalToday").textContent=d.totalToday||0;$("roomContainer").innerHTML=(d.roomStatus||[]).map(r=>`<button class="roomCard ${r.active?"busy":"free"}" onclick="goRoom('${escAttr(r.room)}')"><div class="roomName">${esc(r.room)}</div><div class="roomStatus">${r.active?"🟠 Sampling":"🟢 ว่าง"}</div><div class="roomCount">${r.count||0} รายการ</div></button>`).join("")||'<div class="empty">ไม่มี Room</div>';$("nowBody").innerHTML=s.length?s.map(x=>`<tr><td>${esc(x.room)}</td><td>${esc(x.code)}</td><td>${esc(x.batch)}</td><td>${esc(x.inspector)}</td><td><span class="badge sampling">Sampling</span></td></tr>`).join(""):'<tr><td colspan="5" class="empty">ไม่มีงานที่กำลัง Sampling</td></tr>'}
function goRoom(r){$("historyRoom").value=r;document.querySelector('[data-tab="historyTab"]').click();renderHistory()}
function renderHistory(){const k=$("txtSearch").value.trim().toLowerCase(),room=$("historyRoom").value,status=$("historyStatus").value;const d=allHistory.filter(x=>(!k||[x.code,x.batch,x.room,x.reportIn,x.reportOut,x.status,x.balance].join(" ").toLowerCase().includes(k))&&(!room||x.room===room)&&(!status||x.status===status));$("historyBody").innerHTML=d.length?d.map(x=>`<tr><td>${esc(x.startTime)}</td><td>${esc(x.code)}</td><td>${esc(x.batch)}</td><td>${esc(x.unit)}</td><td>${esc(x.incomingCarton)}</td><td>${esc(x.sampleIn)}</td><td>${esc(x.finishTime)}</td><td>${esc(x.sampleOut)}</td><td>${esc(x.sampleUsage)}</td><td>${balanceBadge(x.balance)}</td><td>${x.approveBy?`<span class="approved">✓ ${esc(x.approveBy)}</span>`:"รอ Approve"}</td></tr>`).join(""):'<tr><td colspan="11" class="empty">ไม่พบข้อมูล</td></tr>'}
function renderSupervisor(){fillApprovers();const room=$("supervisorRoom").value,approver=$("approveBy").value;let d=allHistory.filter(x=>x.status==="Completed"&&!x.approveBy);if(room)d=d.filter(x=>x.room===room);$("approvalBody").innerHTML=d.length?d.map(x=>`<tr><td>${esc(x.startTime)}</td><td>${esc(x.code)}</td><td>${esc(x.batch)}</td><td>${esc(x.room)}</td><td>${esc(x.sampleIn)}</td><td>${esc(x.sampleOut)}</td><td>${esc(x.sampleUsage)}</td><td>${balanceBadge(x.balance)}</td><td><button class="approveBtn" ${!approver?"disabled":""} onclick="approveRow('${escAttr(x.code)}','${escAttr(x.batch)}','${escAttr(x.room)}')">✓ Approve</button></td></tr>`).join(""):'<tr><td colspan="9" class="empty">ไม่มีรายการรอ Approve</td></tr>'}
async function approveRow(code,batch,room){const name=$("approveBy").value;if(!name)return toast("กรุณาเลือกผู้อนุมัติ","error");if(!confirm(`ยืนยัน Approve ${code} / ${batch} โดย ${name} ?`))return;const j=await postJson({action:"approve",code,batch,room,approveBy:name,pin:pinSession});if(!j.success)return toast(j.message,"error");toast("Approve สำเร็จ","success");await loadAll()}
async function saveSampling(){const finish=$("status").value==="Finish Sampling",code=$("code").value.trim().toUpperCase(),batch=$("batch").value.trim().toUpperCase();if(!code||!batch)return toast("กรุณากรอก/สแกน Code และ Batch","error");if(!$("room").value)return toast("กรุณาเลือก Room","error");const btn=$("btnSave");btn.disabled=true;try{let body={action:finish?"finishSampling":"startSampling",room:$("room").value,inspector:$("inspector").value,code,batch,unit:$("unit").value,qrRaw:""};if(!finish){calcStart();body.incomingCarton=$("incomingCarton").value;body.remainderCartonIn=$("remainderCartonIn").value;body.remainderQtyIn=$("remainderQtyIn").value;body.fullCartonIn=$("fullCartonIn").value;body.qtyFullCartonIn=$("qtyFullCartonIn").value;body.remark=$("remarkIn").value.trim()}else{await loadStartForFinish();body.totalCartonOut=$("totalCartonOut").value;body.remainderCartonOut=$("remainderCartonOut").value;body.remainderQtyOut=$("remainderQtyOut").value;body.fullCartonOut=$("fullCartonOut").value;body.qtyFullCartonOut=$("qtyFullCartonOut").value;body.sampleUsage=$("sampleUsage").value;body.remark=$("remarkOut").value.trim()}const j=await postJson(body);if(!j.success)throw Error(j.message);toast(j.message,"success");if(j.data?.balance!==undefined){$("balanceAlert").textContent=j.data.balanceOK?"✅ Balance OK":"⚠️ Balance ต่าง "+j.data.balance;$("balanceAlert").className="balanceAlert "+(j.data.balanceOK?"ok":"bad")}clearForm();await loadAll()}catch(e){toast(e.message||"บันทึกไม่สำเร็จ","error")}finally{btn.disabled=false}}
function clearForm(){["code","batch","incomingCarton","totalCartonIn","remainderQtyIn","fullCartonIn","qtyFullCartonIn","totalCartonOut","remainderQtyOut","fullCartonOut","qtyFullCartonOut","sampleUsage","remarkIn","remarkOut"].forEach(id=>$(id).value="");$("remainderCartonIn").value="0";$("remainderCartonOut").value="0";$("sampleInPreview").textContent="0";$("sampleOutPreview").textContent="0";$("balancePreview").textContent="รอคำนวณ";hiddenIncoming().value=""}
async function addRoom(){const v=$("newRoom").value.trim();if(!v)return toast("กรุณากรอก Room","error");const j=await postJson({action:"addRoom",room:v,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success){$("newRoom").value="";await loadMaster()}}
async function addInspector(){const v=$("newInspector").value.trim();if(!v)return toast("กรุณากรอก Inspector","error");const j=await postJson({action:"addInspector",inspector:v,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success){$("newInspector").value="";await loadMaster()}}
async function addSupervisor(){const name=$("newSupervisor").value.trim();if(!name)return toast("กรุณากรอกชื่อผู้อนุมัติ","error");const j=await postJson({action:"addSupervisor",supervisor:name,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success){$("newSupervisor").value="";await loadMaster()}}
async function deleteRoom(room){const j=await postJson({action:"deleteRoom",room,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success)await loadMaster()}async function deleteInspector(name){const j=await postJson({action:"deleteInspector",inspector:name,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success)await loadMaster()}async function deleteSupervisor(name){const j=await postJson({action:"deleteSupervisor",supervisor:name,pin:pinSession});toast(j.message,j.success?"success":"error");if(j.success)await loadMaster()}
function renderSettings(){$("roomSettings").innerHTML=rooms.map(x=>`<div class="masterRow"><span>${esc(x.room)}</span><button class="dangerBtn" onclick="deleteRoom('${escAttr(x.room)}')">ปิดใช้งาน</button></div>`).join("")||'<div class="empty">ไม่มี Room</div>';$("inspectorSettings").innerHTML=inspectors.map(x=>`<div class="masterRow"><span>${esc(x.inspector)}</span><button class="dangerBtn" onclick="deleteInspector('${escAttr(x.inspector)}')">ปิดใช้งาน</button></div>`).join("")||'<div class="empty">ไม่มี Inspector</div>';$("supervisorSettings").innerHTML=supervisors.map(x=>`<div class="masterRow"><span>${esc(x.supervisor)}</span><button class="dangerBtn" onclick="deleteSupervisor('${escAttr(x.supervisor)}')">ปิดใช้งาน</button></div>`).join("")||'<div class="empty">ยังไม่มีรายชื่อผู้อนุมัติ</div>';$("pinStatusText").textContent=hasPin?"สถานะ PIN: ตั้งค่าแล้ว":"สถานะ PIN: ยังไม่ได้ตั้งค่า"}
function exportCSV(){const h=["วันที่เริ่ม","Material Code","Batch No.","Unit","Incoming Qty","Sampling Size IN","วันที่ออก","Sampling Size OUT","Sampling Usage","Balance","Approve By","Approve Time","Room","Remark"];const d=allHistory.map(x=>[x.startTime,x.code,x.batch,x.unit,x.incomingCarton,x.sampleIn,x.finishTime,x.sampleOut,x.sampleUsage,x.balance,x.approveBy,x.approveTime,x.room,x.remark]);const csv="\uFEFF"+[h,...d].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`Q-Sampling-${new Date().toISOString().slice(0,10)}.csv`;a.click()}
function openScanner(){$("scannerModal").classList.remove("hidden");if(!navigator.mediaDevices?.getUserMedia||typeof jsQR!=="function")return $("scanHint").textContent="อุปกรณ์นี้ไม่พร้อมสำหรับกล้อง";navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}}).then(async s=>{scanStream=s;$("qrVideo").srcObject=s;await $("qrVideo").play();scanCanvas=document.createElement("canvas");scanCtx=scanCanvas.getContext("2d",{willReadFrequently:true});scanTimer=setInterval(scanFrame,180)}).catch(()=>$("scanHint").textContent="กรุณาอนุญาต Camera แล้วลองใหม่")}
function scanFrame(){const v=$("qrVideo");if(!v.videoWidth)return;const w=Math.min(v.videoWidth,900),h=Math.round(v.videoHeight*w/v.videoWidth);scanCanvas.width=w;scanCanvas.height=h;scanCtx.drawImage(v,0,0,w,h);const q=jsQR(scanCtx.getImageData(0,0,w,h).data,w,h,{inversionAttempts:"attemptBoth"});if(q?.data){useQrText(q.data);closeScanner()}}
function useManualQr(){const v=$("qrManual").value.trim();if(v){useQrText(v);closeScanner()}}
function useQrText(raw){const v=String(raw||"").trim();let code="",batch="";try{const o=JSON.parse(v);code=o.code||o.materialCode||o.material_code||o.material||"";batch=o.batch||o.batchNo||o.batch_no||o.batchNumber||""}catch(_){}if(!code||!batch)try{const u=new URL(v),q=u.searchParams;code=code||q.get("code")||q.get("materialCode")||q.get("material_code")||"";batch=batch||q.get("batch")||q.get("batchNo")||q.get("batch_no")||""}catch(_){}if(!code||!batch){const m=v.match(/(?:code|material\s*code)\s*[:=]\s*([^,;|\s]+)[,;|\s]+(?:batch|batch\s*no)\s*[:=]\s*([^,;|\s]+)/i);if(m){code=m[1];batch=m[2]}}if(!code||!batch){const p=v.split(/[|,;]/);if(p.length>=2){code=p[0].trim();batch=p[1].trim()}}if(code){$("code").value=code.toUpperCase();if(batch)$("batch").value=batch.toUpperCase();toast(batch?"สแกน QR สำเร็จ — Code + Batch ถูกเติมแล้ว":"สแกน QR สำเร็จ — เติม Code แล้ว","success");if(batch)loadStartForFinish();return}$("code").value=v.toUpperCase();toast("อ่าน QR แล้ว แต่ยังแยก Batch ไม่ได้","error")}
function closeScanner(){if(scanTimer)clearInterval(scanTimer);scanTimer=null;if(scanStream)scanStream.getTracks().forEach(t=>t.stop());scanStream=null;if($("qrVideo"))$("qrVideo").srcObject=null;$("scannerModal").classList.add("hidden")}
function balanceBadge(v){if(!v)return"";const ok=v.includes("✅");return `<span class="balance ${ok?"ok":"bad"}">${esc(v)}</span>`}function setOnline(){$("serverStatus").className="statusPill online";$("serverStatus").textContent="🟢 Connected"}function setOffline(){$("serverStatus").className="statusPill offline";$("serverStatus").textContent="🔴 Offline"}function toast(m,t="success"){const e=$("toast");e.textContent=m;e.className=`toast show ${t}`;setTimeout(()=>e.classList.remove("show"),3000)}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]))}function escAttr(v){return esc(v).replace(/`/g,"&#096;")}window.goRoom=goRoom;window.approveRow=approveRow;window.deleteRoom=deleteRoom;window.deleteInspector=deleteInspector;window.deleteSupervisor=deleteSupervisor;
